### ISSUE TITLE
[Question/bug?] Solving certain integer problems

### ISSUE THREAD

**Issue by Blacksmoke16** [srcostenoble/simplex#2]
I might be doing something wrong but, say I have the following problem:

```
minimize v = 0.1a + .15b subject to
207a + 173b  >= 2000000
86b >= 500000
```

It correctly solves the problem with solutions `a=4802.831142568 and b=5813.953488372001`

However, when applying integer constraints to a and b, it gives an error saying `No solution with the desired integer values exists` . When i know the integer solutions are `a=4803 and b=5814` from solving it by hand.

Problem that gives the error:
```
minimize v = 0.1a + .15b subject to
207a + 173b  >= 2000000
86b >= 500000
integer a, b
```

Need anything else let me know,
Thanks

**Comment by srcostenoble** [comment]
You found a bug. It should be fixed now, please download the new code and try it again. Thanks.

--Steve

**Comment by Blacksmoke16** [comment]
Great thanks!  Do you know when the web version will be updated?

**Comment by stefman2** [comment]
Hi Blacksmoke16. The web version is now updated as well!

**Comment by stefman2** [comment]
This issue should, I think, be closed, given Steve's successful fix.
